<template>
  <component v-if="isHeroIcon" :is="`${icon}Icon`" aria-hidden="true" />
</template>
<script>
import {
  EyeIcon,
  SparklesIcon,
  CheckBadgeIcon,
  BanknotesIcon,
  ClockIcon,
  RocketLaunchIcon,
  CodeBracketIcon,
  ChatBubbleBottomCenterTextIcon,
  ViewfinderCircleIcon,
  SunIcon,
  MoonIcon,
  MegaphoneIcon as SpeakerphoneIcon,
  SpeakerXMarkIcon as VolumeOffIcon,
  SpeakerWaveIcon as VolumeUpIcon,
  FaceSmileIcon as EmojiHappyIcon,
  FaceFrownIcon as EmojiSadIcon,
  ArrowRightIcon,
  ArrowUturnLeftIcon as ReplyIcon,
  CurrencyDollarIcon,
  CursorArrowRaysIcon as CursorClickIcon,
  ShareIcon,
  ListBulletIcon,
  Cog6ToothIcon as CogIcon,
  FunnelIcon as FilterIcon,
  SwatchIcon as ColorSwatchIcon,
  RectangleStackIcon as CollectionIcon,
  AdjustmentsVerticalIcon,
  HomeIcon,
  LightBulbIcon,
  Bars3CenterLeftIcon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon as MenuAlt3Icon,
  PhotoIcon as PhotographIcon,
  PlusIcon,
  MinusIcon,
  MicrophoneIcon,
  UserGroupIcon,
  Squares2X2Icon as ViewGridIcon,
  XMarkIcon as XIcon,
  ChartBarSquareIcon as ChartSquareBarIcon,
  EnvelopeIcon as MailIcon,
  CalendarIcon,
  UsersIcon,
  UserIcon,
  BuildingOfficeIcon as OfficeBuildingIcon,
  FolderIcon,
  CheckCircleIcon,
  CheckIcon,
  XCircleIcon,
  SquaresPlusIcon,
  InformationCircleIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ExclamationTriangleIcon,
  ShieldExclamationIcon,
  ShieldCheckIcon,
  QuestionMarkCircleIcon,
  BellIcon,
  ArrowsPointingOutIcon,
  ChevronUpDownIcon as SelectorIcon,
  ArrowPathIcon as RefreshIcon,
  DocumentDuplicateIcon as DuplicateIcon,
  GlobeAsiaAustraliaIcon as GlobeIcon,
  DevicePhoneMobileIcon as DeviceMobileIcon,
  PhoneIcon,
  PhoneXMarkIcon,
  EllipsisVerticalIcon as DotsVerticalIcon,
  EllipsisHorizontalIcon as DotsHorizontalIcon,
  DocumentArrowDownIcon as DocumentDownloadIcon,
  DocumentPlusIcon as DocumentAddIcon,
  DocumentIcon,
  DocumentTextIcon,
  ArrowDownLeftIcon,
  ArrowDownTrayIcon as DownloadIcon,
  ArrowTopRightOnSquareIcon as ExternalLinkIcon,
  LinkIcon,
  TrashIcon,
  PencilSquareIcon as PencilAltIcon,
  PencilIcon,
  StarIcon,
  Bars3Icon,
  TagIcon,
  ViewColumnsIcon,
  BarsArrowUpIcon as SortAscendingIcon,
  AtSymbolIcon,
  BriefcaseIcon,
  ChatBubbleOvalLeftEllipsisIcon as ChatIcon,
  ChatBubbleLeftEllipsisIcon as ChatAltIcon,
  BookOpenIcon,
  BookmarkIcon,
  CameraIcon,
  TruckIcon,
  CloudArrowUpIcon,
  PaperClipIcon,
  ClipboardIcon,
  CreditCardIcon,
  WrenchScrewdriverIcon,
  ScaleIcon,
} from '@heroicons/vue/24/outline'
import {
  MagnifyingGlassIcon as SearchSolidIcon,
  CheckCircleIcon as CheckCircleSolidIcon,
  XCircleIcon as XCircleSolidIcon,
} from '@heroicons/vue/20/solid'
export default {
  components: {
    EyeIcon,
    SparklesIcon,
    CheckBadgeIcon,
    BanknotesIcon,
    ClockIcon,
    CodeBracketIcon,
    RocketLaunchIcon,
    ChatBubbleBottomCenterTextIcon,
    ViewfinderCircleIcon,
    SunIcon,
    MoonIcon,
    SpeakerphoneIcon,
    VolumeOffIcon,
    VolumeOffIcon,
    VolumeUpIcon,
    EmojiHappyIcon,
    EmojiSadIcon,
    ArrowRightIcon,
    ReplyIcon,
    CurrencyDollarIcon,
    CursorClickIcon,
    FilterIcon,
    ShareIcon,
    ListBulletIcon,
    CogIcon,
    CollectionIcon,
    ColorSwatchIcon,
    HomeIcon,
    LightBulbIcon,
    Bars3CenterLeftIcon,
    Bars3BottomLeftIcon,
    MenuAlt3Icon,
    PhotographIcon,
    PlusIcon,
    MinusIcon,
    MicrophoneIcon,
    UserGroupIcon,
    ViewGridIcon,
    XIcon,
    SearchSolidIcon,
    ChartSquareBarIcon,
    MailIcon,
    CalendarIcon,
    UsersIcon,
    UserIcon,
    OfficeBuildingIcon,
    FolderIcon,
    CheckCircleIcon,
    CheckCircleSolidIcon,
    CheckIcon,
    XCircleIcon,
    XCircleSolidIcon,
    InformationCircleIcon,
    ChevronUpIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ExclamationTriangleIcon,
    ShieldExclamationIcon,
    ShieldCheckIcon,
    SquaresPlusIcon,
    QuestionMarkCircleIcon,
    SelectorIcon,
    BellIcon,
    ArrowsPointingOutIcon,
    RefreshIcon,
    DuplicateIcon,
    GlobeIcon,
    DeviceMobileIcon,
    PhoneIcon,
    PhoneXMarkIcon,
    AdjustmentsVerticalIcon,
    DotsVerticalIcon,
    DotsHorizontalIcon,
    DocumentDownloadIcon,
    DocumentAddIcon,
    DocumentIcon,
    DocumentTextIcon,
    ArrowDownLeftIcon,
    DownloadIcon,
    ExternalLinkIcon,
    LinkIcon,
    TrashIcon,
    PencilAltIcon,
    PencilIcon,
    StarIcon,
    Bars3Icon,
    TagIcon,
    ViewColumnsIcon,
    SortAscendingIcon,
    AtSymbolIcon,
    BriefcaseIcon,
    ChatIcon,
    ChatAltIcon,
    BookOpenIcon,
    BookmarkIcon,
    CameraIcon,
    TruckIcon,
    CloudArrowUpIcon,
    PaperClipIcon,
    ClipboardIcon,
    CreditCardIcon,
    WrenchScrewdriverIcon,
    ScaleIcon,
  },
  props: {
    type: {
      type: String,
      default: 'hero',
    },
    icon: {
      required: true,
    },
  },
  setup(props) {
    function isHeroIcon() {
      return props.type === 'hero'
    }

    return {
      isHeroIcon,
    }
  },
}
</script>
